version: '3.12'

services:
  frontend:
    build: ./frontend
    ports:
      - "8501:8501"
    volumes:
      - ./frontend:/app
      - ./types:/app/types  # Mount the types directory for access to type images
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:8000

  backend:
    build: ./backend
    volumes:
      - ./backend:/backend
      - ./pokemon_data.json:/backend/pokemon_data.json  # Mount the Pokemon data
    ports:
      - "8000:8000"  # Expose the API port